# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raddress.proto\"t\n\x0b\x61\x64\x64ress_obj\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06street\x18\x02 \x01(\t\x12\x0e\n\x06number\x18\x03 \x01(\x05\x12\x0c\n\x04\x63ity\x18\x04 \x01(\t\x12\r\n\x05state\x18\x05 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x06 \x01(\t\x12\x0b\n\x03zip\x18\x07 \x01(\t\"\x19\n\x0bget_request\x12\n\n\x02id\x18\x01 \x01(\t\"\x0e\n\x0clist_request2\xcf\x01\n\x07\x41\x64\x64ress\x12&\n\x06\x63reate\x12\x0c.address_obj\x1a\x0c.address_obj\"\x00\x12&\n\x06update\x12\x0c.address_obj\x1a\x0c.address_obj\"\x00\x12#\n\x03get\x12\x0c.get_request\x1a\x0c.address_obj\"\x00\x12\'\n\x04list\x12\r.list_request\x1a\x0c.address_obj\"\x00\x30\x01\x12&\n\x06\x64\x65lete\x12\x0c.get_request\x1a\x0c.address_obj\"\x00\x62\x06proto3')



_ADDRESS_OBJ = DESCRIPTOR.message_types_by_name['address_obj']
_GET_REQUEST = DESCRIPTOR.message_types_by_name['get_request']
_LIST_REQUEST = DESCRIPTOR.message_types_by_name['list_request']
address_obj = _reflection.GeneratedProtocolMessageType('address_obj', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS_OBJ,
  '__module__' : 'address_pb2'
  # @@protoc_insertion_point(class_scope:address_obj)
  })
_sym_db.RegisterMessage(address_obj)

get_request = _reflection.GeneratedProtocolMessageType('get_request', (_message.Message,), {
  'DESCRIPTOR' : _GET_REQUEST,
  '__module__' : 'address_pb2'
  # @@protoc_insertion_point(class_scope:get_request)
  })
_sym_db.RegisterMessage(get_request)

list_request = _reflection.GeneratedProtocolMessageType('list_request', (_message.Message,), {
  'DESCRIPTOR' : _LIST_REQUEST,
  '__module__' : 'address_pb2'
  # @@protoc_insertion_point(class_scope:list_request)
  })
_sym_db.RegisterMessage(list_request)

_ADDRESS = DESCRIPTOR.services_by_name['Address']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDRESS_OBJ._serialized_start=17
  _ADDRESS_OBJ._serialized_end=133
  _GET_REQUEST._serialized_start=135
  _GET_REQUEST._serialized_end=160
  _LIST_REQUEST._serialized_start=162
  _LIST_REQUEST._serialized_end=176
  _ADDRESS._serialized_start=179
  _ADDRESS._serialized_end=386
# @@protoc_insertion_point(module_scope)
